#!/usr/bin/env bun
// Fetches the gemoji database (same source ntfy uses) and generates src/emojis.ts.
// Run with: bun run generate:emojis

const GEMOJI_URL = "https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json"
const OUT_PATH = new URL("../src/emojis.ts", import.meta.url).pathname

type GemojiEntry = {
  emoji: string
  aliases: string[]
}

console.log("Fetching gemoji database...")
const res = await fetch(GEMOJI_URL)
if (!res.ok) throw new Error(`Failed to fetch: ${res.status}`)

const entries = (await res.json()) as GemojiEntry[]

const lines: string[] = []
for (const { emoji, aliases } of entries) {
  for (const alias of aliases) {
    if (alias) lines.push(`  ${JSON.stringify(alias)}: ${JSON.stringify(emoji)},`)
  }
}

const output = `// Auto-generated by scripts/generate-emojis.ts — do not edit manually.
// Source: https://github.com/github/gemoji/blob/master/db/emoji.json
// Run \`bun run generate:emojis\` to regenerate.

export const EMOJI_MAP: Record<string, string> = {
${lines.join("\n")}
}
`

await Bun.write(OUT_PATH, output)
console.log(`Written ${lines.length} entries to src/emojis.ts`)
